version: "3.8"
services:
  can-database:
    container_name: "can-database"
    image: "microsoft/mssql-server-linux:2017-latest"
    ports:
      - "1433:1433"
    volumes:
      - can-database-mssql:/var/opt/mssql/data

volumes:
  can-database-mssql:
